### ISSUE TITLE
Build error and out of date dependencies

### ISSUE THREAD

**Issue by keyscores** [linitix/autoingesttool#2]
Thanks for porting this library. Any chance you can check the travis build status and dependency status. 
Hopefully I can contribute back once you have that up to date.
Thanks again!

**Comment by igorissen** [comment]
Hi @keyscores,

I just updated the dependencies. On the other hand, I deleted the badge and configuration file of the service TravisCI. I think that for the moment I do not have the usefulness of this service.
You can close this issue If it's ok for you.

Thanks for reporting this issue.

**Comment by keyscores** [comment]
Thanks!
I do very much like the idea o continuous testing of the package. Its
especially good if for example I were to collaborate. But I understand if
it is too much to maintain for a small script.
Thanks again for this contribution.

**Comment by igorissen** [comment]
If you want I can put back the TravisCI configuration file for you to make some pull requests.

**Comment by keyscores** [comment]
Since you already went through the trouble I recommend keeping it. If you
could write a simple initial test, we could extend it when we start working
on this.
Thanks again!

Lucas Geiger
